[connections.snowflake]
account = "TVVDLYG-ZDB56418"
user = "tlegallformation"
password = "Motdepasse29@formation"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
